export const college = {
  name: 'Fatima Girls College',
  short_name: 'FGC',
  location: 'Aminpur Bangla',
  tagline: 'Empowering Women Through Education',
  address: 'Opposite to Molana Muhammad Zakir Degree College, Aminpur Bangla',
  phone: '03214251905',
  phone_display: '0321 4251905',
  email: 'fgcollege86@gmail.com',
  office_hours: 'Monday – Saturday, 8:00 AM – 2:00 PM',
  map_query: 'Molana Muhammad Zakir Degree College Aminpur Bangla',
  religions: ['Islam', 'Christianity', 'Hinduism', 'Sikhism', 'Other'],
  nationalities: [
    'Afghan', 'Albanian', 'Algerian', 'American', 'Argentine', 'Australian',
    'Austrian', 'Bangladeshi', 'Belgian', 'Brazilian', 'British', 'Canadian',
    'Chinese', 'Danish', 'Dutch', 'Egyptian', 'Emirati', 'Filipino', 'Finnish',
    'French', 'German', 'Ghanaian', 'Greek', 'Indian', 'Indonesian', 'Iranian',
    'Iraqi', 'Irish', 'Italian', 'Japanese', 'Jordanian', 'Kazakh', 'Kenyan',
    'Korean', 'Kuwaiti', 'Lebanese', 'Libyan', 'Malaysian', 'Mexican', 'Moroccan',
    'Nepali', 'Nigerian', 'Norwegian', 'Omani', 'Pakistani', 'Palestinian',
    'Polish', 'Portuguese', 'Qatari', 'Romanian', 'Russian', 'Saudi',
    'Singaporean', 'Somali', 'South African', 'Spanish', 'Sri Lankan', 'Sudanese',
    'Swedish', 'Swiss', 'Syrian', 'Thai', 'Tunisian', 'Turkish', 'Ukrainian',
    'Uzbek', 'Vietnamese', 'Yemeni',
  ],
  boards: [
    'BISE Lahore', 'BISE Faisalabad', 'BISE Rawalpindi', 'BISE Multan', 'BISE Sargodha',
    'BISE Gujranwala', 'BISE Bahawalpur', 'BISE Dera Ghazi Khan', 'BISE Sahiwal',
    'Punjab Board of Technical Education (PBTE)',
    'Federal Board of Intermediate and Secondary Education (FBISE)',
    'Aga Khan University Examination Board (AKU-EB)',
    'Board of Intermediate Education Karachi (BIEK)',
    'Board of Secondary Education Karachi (BSEK)',
    'BISE Hyderabad', 'BISE Sukkur', 'BISE Larkana', 'BISE Mirpurkhas', 'BISE Shaheed Benazirabad',
    'Sindh Board of Technical Education (SBTE)',
    'BISE Peshawar', 'BISE Mardan', 'BISE Abbottabad', 'BISE Kohat', 'BISE Bannu',
    'BISE Dera Ismail Khan', 'BISE Malakand', 'BISE Swat',
    'Khyber Pakhtunkhwa Board of Technical Education (KPBTE)',
    'BISE Quetta', 'BISE Zhob', 'BISE Turbat', 'BISE Kalat', 'BISE Sibi',
    'Balochistan Board of Technical Education',
    'BISE Mirpur AJK', 'BISE Kotli AJK', 'BISE Gilgit-Baltistan',
    'Cambridge Assessment International Education (CAIE)',
    'Pearson Edexcel', 'OxfordAQA', 'Other',
  ],
};
