export const districts = {
  Punjab: ['Attock','Bahawalnagar','Bahawalpur','Bhakkar','Chakwal','Chiniot','Dera Ghazi Khan','Faisalabad','Gujranwala','Gujrat','Hafizabad','Jhang','Jhelum','Kasur','Khanewal','Khushab','Lahore','Layyah','Lodhran','Mandi Bahauddin','Mianwali','Multan','Muzaffargarh','Nankana Sahib','Narowal','Okara','Pakpattan','Rahim Yar Khan','Rajanpur','Rawalpindi','Sahiwal','Sargodha','Sheikhupura','Sialkot','Toba Tek Singh','Vehari'],
  Sindh: ['Badin','Dadu','Ghotki','Hyderabad','Jacobabad','Jamshoro','Karachi Central','Karachi East','Karachi South','Karachi West','Kashmore','Keamari','Khairpur','Korangi','Larkana','Malir','Matiari','Mirpurkhas','Naushahro Feroze','Qambar Shahdadkot','Sanghar','Shaheed Benazirabad','Shikarpur','Sujawal','Sukkur','Tando Allahyar','Tando Muhammad Khan','Tharparkar','Thatta','Umerkot'],
  'Khyber Pakhtunkhwa': ['Abbottabad','Bajur','Bannu','Battagram','Buner','Charsadda','Chitral Lower','Chitral Upper','Dera Ismail Khan','Hangu','Haripur','Karak','Khyber','Kohat','Kolai Palas','Kurram','Lakki Marwat','Lower Dir','Malakand','Mansehra','Mardan','Mohmand','North Waziristan','Nowshera','Orakzai','Peshawar','Shangla','South Waziristan','Swabi','Swat','Tank','Torghar','Upper Dir'],
  Balochistan: ['Awaran','Barkhan','Chagai','Dera Bugti','Duki','Gwadar','Harnai','Hub','Jafarabad','Jhal Magsi','Kachhi','Kalat','Kech','Kharan','Khuzdar','Killa Abdullah','Killa Saifullah','Kohlu','Lasbela','Loralai','Mastung','Musakhel','Nasirabad','Nushki','Panjgur','Pishin','Quetta','Sherani','Sibi','Sohbatpur','Washuk','Zhob','Ziarat'],
  'Islamabad Capital Territory': ['Islamabad'],
  'Gilgit-Baltistan': ['Astore','Diamer','Ghanche','Ghizer','Gilgit','Hunza','Kharmang','Nagar','Shigar','Skardu'],
  'Azad Jammu & Kashmir': ['Bagh','Bhimber','Hattian Bala','Haveli','Kotli','Mirpur','Muzaffarabad','Neelum','Poonch','Sudhnati'],
};

export const tehsils = {
  Attock: ['Attock','Fateh Jang','Hasan Abdal','Hazro','Jand','Pindi Gheb'],
  Bahawalnagar: ['Bahawalnagar','Chishtian','Fort Abbas','Haroonabad','Minchinabad'],
  Bahawalpur: ['Ahmadpur East','Bahawalpur City','Bahawalpur Saddar','Hasilpur','Khairpur Tamewali','Yazman'],
  Bhakkar: ['Bhakkar','Darya Khan','Kalur Kot','Mankera'],
  Chakwal: ['Chakwal','Choa Saidan Shah','Kallar Kahar','Lawa','Talagang'],
  Chiniot: ['Bhowana','Chiniot','Lalian'],
  'Dera Ghazi Khan': ['Dera Ghazi Khan','Koh-e-Suleman','Kot Chutta','Taunsa'],
  Faisalabad: ['Chak Jhumra','Faisalabad City','Faisalabad Saddar','Jaranwala','Samundri','Tandlianwala'],
  Gujranwala: ['Gujranwala City','Gujranwala Saddar','Kamoke','Nowshera Virkan','Wazirabad'],
  Gujrat: ['Gujrat','Jalalpur Jattan','Kharian','Sarai Alamgir'],
  Hafizabad: ['Hafizabad','Pindi Bhattian'],
  Jhang: ['18 Hazari','Ahmadpur Sial','Jhang','Shorkot'],
  Jhelum: ['Dina','Jhelum','Pind Dadan Khan','Sohawa'],
  Kasur: ['Chunian','Kasur','Kot Radha Kishan','Pattoki'],
  Khanewal: ['Jahanian','Kabirwala','Khanewal','Mian Channu'],
  Khushab: ['Khushab','Naushera','Noorpur Thal','Quaidabad'],
  Lahore: ['Lahore Cantt','Lahore City','Model Town','Raiwind','Shalimar','Wagha'],
  Layyah: ['Chaubara','Karor Lal Esan','Layyah'],
  Lodhran: ['Dunyapur','Kahror Pacca','Lodhran'],
  'Mandi Bahauddin': ['Malakwal','Mandi Bahauddin','Phalia'],
  Mianwali: ['Isa Khel','Mianwali','Piplan'],
  Multan: ['Jalalpur Pirwala','Multan City','Multan Saddar','Shujabad'],
  Muzaffargarh: ['Alipur','Jatoi','Kot Addu','Muzaffargarh'],
  'Nankana Sahib': ['Nankana Sahib','Sangla Hill','Shahkot'],
  Narowal: ['Narowal','Shakargarh','Zafarwal'],
  Okara: ['Depalpur','Okara','Renala Khurd'],
  Pakpattan: ['Arifwala','Pakpattan'],
  'Rahim Yar Khan': ['Khanpur','Liaquatpur','Rahim Yar Khan','Sadiqabad'],
  Rajanpur: ['Jampur','Rajanpur','Rojhan'],
  Rawalpindi: ['Gujar Khan','Kahuta','Kallar Syedan','Kotli Sattian','Murree','Rawalpindi','Taxila'],
  Sahiwal: ['Chichawatni','Sahiwal'],
  Sargodha: ['Bhalwal','Bhera','Kot Momin','Sahiwal Sargodha','Sargodha','Shahpur','Sillanwali'],
  Sheikhupura: ['Ferozewala','Muridke','Safdarabad','Sharaqpur','Sheikhupura'],
  Sialkot: ['Daska','Pasrur','Sambrial','Sialkot'],
  'Toba Tek Singh': ['Gojra','Kamalia','Pir Mahal','Toba Tek Singh'],
  Vehari: ['Burewala','Mailsi','Vehari'],
  Hyderabad: ['Hyderabad City','Hyderabad Rural','Latifabad','Qasimabad'],
  'Karachi Central': ['Gulberg','Liaquatabad','Nazimabad','New Karachi','North Nazimabad'],
  'Karachi East': ['Ferozabad','Gulshan-e-Iqbal','Gulzar-e-Hijri','Jamshed Quarters'],
  'Karachi South': ['Aram Bagh','Garden','Lyari','Saddar'],
  'Karachi West': ['Baldia','Mominabad','Orangi','Site'],
  Peshawar: ['Peshawar City','Peshawar Saddar'],
  Quetta: ['Quetta City','Quetta Saddar'],
  Islamabad: ['Islamabad'],
  Gilgit: ['Gilgit','Danyore'],
  Mirpur: ['Mirpur','Dadyal'],
  Muzaffarabad: ['Muzaffarabad','Nasirabad'],
};
